#!/bin/bash

LOG_FILE="/root/actions.txt"

log_action() {
  echo "$(date): $1" >> "$LOG_FILE"
}

list_users() {
  users=$(cut -d: -f1 /etc/passwd)
  menu_items=()
  for user in $users; do
    menu_items+=("$user" "$user")
  done

  dialog --backtitle "ExOS User Management" --stdout --menu "Select a user" 20 50 15 "${menu_items[@]}"
}

list_human_users() {
  human_users=$(awk -F: '($3 >= 1000 && $3 < 65534) {print $1}' /etc/passwd)
  menu_items=()
  for user in $human_users; do
    menu_items+=("$user" "$user")
  done

  dialog --backtitle "ExOS User Management" --stdout --menu "Select a user" 20 50 15 "${menu_items[@]}"
}

view_user_stats() {
  local user=$1
  if id "$user" &>/dev/null; then
    sudo_status=$(groups "$user" | grep -qwE 'sudo|wheel' && echo "Yes" || echo "No")
    groups=$(id -nG "$user")
    last_login=$(lastlog -u "$user" | awk 'NR==2 {print $4, $5, $6, $7}')
    ssh_sources=$(last -i "$user" | awk '{print $3}' | grep -v '^$' | sort -u)
    
    ssh_info=""
    for ip in $ssh_sources; do
      whois_output=$(whois "$ip" | grep -m 1 "OrgName\|country")
      ssh_info+="$ip - $whois_output\n"
    done

    dialog --msgbox "User: $user\nSudo: $sudo_status\nGroups: $groups\nLast Login: ${last_login:-Never}\nSSH Sources:\n${ssh_info:-None}" 20 70
  else
    dialog --msgbox "Error: User '$user' does not exist." 10 50
  fi
}

toggle_sudo() {
  local user=$1
  if id "$user" &>/dev/null; then
    if groups "$user" | grep -qw sudo; then
      sudo deluser "$user" sudo
      log_action "Removed sudo privileges from $user."
      dialog --msgbox "Removed sudo privileges from $user." 10 40
    else
      sudo adduser "$user" sudo
      log_action "Granted sudo privileges to $user."
      dialog --msgbox "Granted sudo privileges to $user." 10 40
    fi
  else
    dialog --msgbox "User $user does not exist." 10 40
  fi
}

remove_user() {
  local user=$1
  if id "$user" &>/dev/null; then
    dialog --yesno "Are you sure you want to remove $user?" 10 40
    if [[ $? -eq 0 ]]; then
      dialog --yesno "Do you want to delete the home directory for $user?" 10 40
      local delete_home=$?
      if [[ $delete_home -eq 0 ]]; then
        sudo userdel -r "$user"
        log_action "User $user and home directory deleted."
      else
        sudo userdel "$user"
        log_action "User $user deleted but home directory kept."
      fi
      dialog --msgbox "User $user has been removed." 10 40
    fi
  else
    dialog --msgbox "User $user does not exist." 10 40
  fi
}

add_user() {
  while true; do
    new_user=$(dialog --backtitle "ExOS User Management" --stdout --inputbox "Enter the new username:" 10 40)
    if [[ $? -ne 0 ]]; then
      break
    fi
    if [[ -n $new_user ]]; then
      if sudo useradd -m "$new_user" && sudo passwd "$new_user"; then
        log_action "User $new_user added."
        dialog --msgbox "User $new_user has been added." 10 40
      else
        dialog --msgbox "Failed to add user $new_user. Please check your input." 10 40
      fi
    else
      dialog --msgbox "No username provided. Returning to the Add User menu." 10 40
    fi
  done
}

change_password() {
  local user=$1
  if id "$user" &>/dev/null; then
    sudo passwd "$user"
    log_action "Password changed for user $user."
    dialog --msgbox "Password changed for $user." 10 40
  else
    dialog --msgbox "User $user does not exist." 10 40
  fi
}

lock_user() {
  local user=$1
  if id "$user" &>/dev/null; then
    sudo usermod -s /sbin/nologin "$user"
    log_action "Locked user $user."
    dialog --msgbox "User $user has been locked." 10 40
  else
    dialog --msgbox "User $user does not exist." 10 40
  fi
}

unlock_user() {
  local user=$1
  if id "$user" &>/dev/null; then
    sudo usermod -s /bin/bash "$user"
    log_action "Unlocked user $user."
    dialog --msgbox "User $user has been unlocked." 10 40
  else
    dialog --msgbox "User $user does not exist." 10 40
  fi
}

list_locked_users() {
  locked_users=$(awk -F: '$7 == "/sbin/nologin" {print $1}' /etc/passwd)
  dialog --msgbox "Locked Users:\n${locked_users:-None}" 15 50
}

while true; do
  action=$(dialog --backtitle "ExOS User Management" --stdout --menu "User Management" 20 50 10 \
    1 "List All Users" \
    2 "List Human Users" \
    3 "Add User" \
    4 "List Locked Users" \
    5 "Exit")

  case $action in
    1|2)
      while true; do
        user=$([[ $action -eq 1 ]] && list_users || list_human_users)
        if [[ -z $user ]]; then break; fi
        
        choice=$(dialog --backtitle "ExOS User Management" --stdout --menu "Manage $user" 20 50 10 \
          1 "View Stats" \
          2 "Toggle Sudo Privileges" \
          3 "Remove User" \
          4 "Change Password" \
          5 "Lock User" \
          6 "Unlock User")

        case $choice in
          1) view_user_stats "$user" ;;
          2) toggle_sudo "$user" ;;
          3) remove_user "$user" ;;
          4) change_password "$user" ;;
          5) lock_user "$user" ;;
          6) unlock_user "$user" ;;
        esac
      done
      ;;
    3) add_user ;;
    4) list_locked_users ;;
    5) break ;;
  esac
done
